services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=/api
    ports:
      - "8080:80"

    container_name: frontend-dev

    environment:
      - VITE_BACKEND_URL=/api
    restart: unless-stopped
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
      - ./vite.config.js:/usr/src/app/vite.config.js
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./node_modules:/usr/src/app/node_modules
