services:
  todo-frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: /api
    image: todo-frontend:prod
    container_name: todo-frontend-prod
    restart: unless-stopped

  todo-backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    image: todo-backend:prod
    container_name: todo-backend-prod
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongo:27017/the_database
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    container_name: mongo-prod
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: redis-prod
    restart: unless-stopped
    volumes:
      - redis-data:/data

  nginx:
    image: nginx:alpine
    container_name: nginx-prod
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - todo-frontend
      - todo-backend

volumes:
  mongo-data:
  redis-data:
